### ISSUE TITLE
Problems with updates

### ISSUE THREAD

**Issue by aficiomaquinas** [linuxserver/docker-jackett#106]
I'm having trouble with auto updates. I'm creating my docker on Win 10.

`docker create --name=jackett -e TZ=America/Mexico_City -e AUTO_UPDATE=true -p 9117:9117 -v W:/JackettConfig/config:/config -v C:/Users/Victor/Downloads:/downloads --restart unless-stopped linuxserver/jackett:development`

```
10-23 20:54:44 Info Checking for updates... Jackett variant: CoreLinuxAmdx64
10-23 20:54:44 Info Updates are disabled via --NoUpdates.
```

I submitted [a bug on Jackett](https://github.com/Jackett/Jackett/issues/9037), but it turns out this version is outdated.

**Comment by Roxedus** [comment]
The Issue template exists for a reason, please use it next time.

I would appreciate a reply with the following info:

* Your container build-number, you can get it with `docker inspect -f '{{ index .Config.Labels "build_version" }}' jackett`
* The full container log, you can get it with `docker logs jackett`

**Comment by aficiomaquinas** [comment]
I apologize.

## Steps to Reproduce
1.  Configure Beyond.hd
2.  Test Beyond.hd (Gives error, refer to https://github.com/Jackett/Jackett/issues/9037)
3. Click the yellow 'Check for updates' button on Jackett main screen.

## Environment
OS Name:                   Microsoft Windows 10 Enterprise LTSC
OS Version:                10.0.17763 N/A Build 17763
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 13 GenuineIntel ~3600 Mhz

**How docker service was installed:**
From the official docker repo.
The jackett service is created in powershell, then started on Docker Desktop.

## Command used to create docker container (run/create/compose/screenshot)
`docker create --name=jackett -e TZ=America/Mexico_City -e AUTO_UPDATE=true -p 9117:9117 --restart unless-stopped linuxserver/jackett:development`

## Docker inspect build version
```
docker inspect -f '{{ index .Config.Labels "build_version" }}' jackett
Template parsing error: template: :1: function "build_version" not defined
```

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
10-23 21:26:30 Info Starting Jackett v0.16.795.0
10-23 21:26:31 Info Environment version: 3.1.5 (/app/Jackett/)
10-23 21:26:31 Info OS version: Unix 4.19.76.0 (64bit OS) (64bit process)
10-23 21:26:31 Info Jackett variant: CoreLinuxAmdx64
10-23 21:26:31 Info File /etc/issue: Ubuntu 18.04.4 LTS \n \l
10-23 21:26:31 Info Running in Docker: Yes
10-23 21:26:31 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
10-23 21:26:31 Info App config/log directory: /config/Jackett
10-23 21:26:31 Info Using Proxy: No
10-23 21:26:31 Error Your version of Jackett v0.16.795.0 is very old. Multiple indexers are likely to fail when using an old version. Update to the latest version of Jackett.
10-23 21:26:31 Info Using HTTP Client: HttpWebClient2NetCore
10-23 21:26:31 Info Loading Cardigann definitions from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
10-23 21:26:33 Info Cardigann definitions loaded: abnormal, alpharatio, anidex, anidub, animebytes, animetorrents, anthelion, avistaz, awesomehd, bakabt, bb, bitcityreloaded, bithdtv, bjshare, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, corsarored, danishbits, digitalcore, digitalhive, divxtotal, elitetracker, epublibre, exoticaz, filelist, funfile, fuzer, gazellegames, gimmepeers, hdbitsapi, hdonly, hdspace, hdtorrents, hebits, horriblesubs, icetorrent, immortalseed, internetarchive, iptorrents, lostfilm, mejortorrent, milkie, morethantv, myamity, myanonamouse, ncore, nebulance, newpct, newrealworld, norbits, nordicbits, notwhatcd, orpheus, partis, passthepopcorn, pier720, piratethenet, pixelhd, polishtracker, pornolab, pretome, privatehd, psytorrents, rarbg, redacted, revolutiontt, rutracker, scenefz, scenehd, scenetime, secretcinema, shazbat, showrss, solidtorrents, speedcd, superbits, toloka, torrentbytes, torrentday, torrentech, torrentheaven, torrentleech, torrentnetwork, torrentscsv, torrentseeds, torrentsyndikat, tvstore, tvvault, xspeeds, xthor, xtremezone, yts, animetosho, yingk, focusx, peersfm, Das-Unerwartete, hddolby, mteamtp, btnext, uniongang, badasstorrents, omgwtftrackr, hddisk, torrentslocal, audiobooktorrents, acgsou, pirateiro, glodls, 3dtorrents, desireleasers, generationfree, eztv, twilightszoom, hdchina, empornium, idope, shareuniversity, torrenting, pornbits, torrent9clone, kinorun, xbytesv2, vizuk, firebit, turkseed, erzsebetpl, ehentai, gay-torrents, p2pelite, mononokebt, thevault, uhdbits, theaudioscene, wihd, hdcenter, nethd, wdt, pornolive, theshinning, insanetracker, yggtorrent, torrent4you, zamundanet, torrentkitty, bithumen, finvip, scenerush, pornbay, lechaudron, spiritofrevolution, cinematik, bithorlo, kaztorka, moecat, ourbits, pt99, hdc, twilight, academictorrents, libranet, limetorrents, zooqle, skytorrentsclone, zetorrents, onejav, asiancinema, bluebirdhd, hush, elitetorrent-biz, gfxpeers, lesaloon, bitturk, diablotorrent, mteamtp2fa, downloadville, thegeeks, noname-club, crazyspirits, magnet4you, itorrent, torrentseed, haidan, ydypt, totheglory, toros, thehorrorcharnel, rustorka, demonoid, shellife, torrentfunk, piratbit, movcr, empornium2fa, onlyscene, efectodoppler, topnow, ebooks-shares, takeabyte, 52pt, legacyhd, freetorrent, torrentland, torrentz2, sharewood, pwtorrents, legittorrents, thefallingangels, femdomcult, tvchaosuk, dragonworldreloaded, torrentdb, torlock, linkomanija, pornotor, torrentv, myspleen, 3evils, sdbits, demonsite, hdbitscom, ptmsg, btdb, galeriens, ethor, kapaki, greekteam, uniondht, crazyhd, hdcity, snowpt, dxp, casatorrent, darktracker, carpathians, eniahd, hd4fans, btgigs, bigfangroup, hdbits, newretro, Bittorrentfiles, ettv, audiobookbay, cztorrent, dmhy, kickasstorrent-kathow, theempire, fantasticheaven, booktracker, speedtorrentreloaded, marinetracker, moviesdvdr, rutracker-ru, cpasbien, tenyardtracker, mvgroupmain, xwtclassics, epizod, torrentproject2, bigtower, hqsource, torrent9, 4thd, soulvoice, magico, bteye, casstudiotv, alexfilm, newstudiol, torrentdownloads, zelkaorg, xfsub, film-paleis, underverse, oxtorrent, xxxtor, hdu, ebookparadijs, gamestorrents, yourbittorrent, extremebits, classix, anisource, brasiltracker, mvgroupforum, documentarytorrents, beyond-hd-oneurl, chilebt, tellytorrent, totallykids, u2, p2pbg, netcosmo, torrentccf, exttorrents, hdroute, torrentgalaxyorg, proaudiotorrents, 3changtrai, esharenet, datascene, torrent-pirat, concertos, scenepalace, gaytorrentru, r3vwtf, monova, hdsky, dxdhd, hamsterstudio, torrentparadise, crnaberza, baibako, learnflakes, bit-titan, hdhome, Channelx, bwtorrents, rptorrents, theoccult, tokyotosho, ttsweb, torrentlt, filebase, tasmanit, nyaa-pantsu, liaorencili, exkinoray, btetree, audionews, rus-media, keepfriends, hdtime, chdbits, tjupt, kinonavse100, 7torrents, nyaasi, siambit, nntt, purovicio, pthome, funkytorrents, acidlounge, racingforme, teamhd, bitru, blutopia, torrentview, muziekfabriek, teamos, ccfbits, rintor, iv-torrents, sportscult, ibit, rutor, parnuxi, nitro, theshow, ztracker, concen, newstudio, hdspain, divteam, aither, torrentfactory, sosulki, pornorip, torrentoyunindir, hdarea, 2fast4you, bigtorrent, world-of-tomorrow, gigatorrents, pctorrent, hdme, dark-shadow, torrentdownload, trancetraffic, hdolimpo, nbtorrents, puntorrent, majomparade, losslessclub, btsow, girotorrent, oshenpt, arabp2p, cinemamovies, seedfile, torrenthane, hdforever, btdigg, uniotaku, brobits, mypornclub, arenabg, u-torrents, 1337x, boxingtorrents, tekno3d, piratbitl, btschool, torrent-explosiv, horrorsite, pixelcove, turktorrent, shareisland, spacetorrent, jpopsuki, ast4u, torrenthr, backups, lastfiles, deildu, acgrip, kinozal, xwtorrents, sktorrent-org, pornleech, arabafenice, finelite, rapidzona, extremetorrents, racing4everyone, fullmixmusic, unlimitz, sporthd, erzsebet, xxxtorrents, hdzone, vhstapes, shokweb, bibliotik, tribalmixes, retroflix, filmsclub, pornforall, unionfansub, fanoin, inperil, riperam, leaguehd, torrentsectorcrew, ptsbao, isohunt2, frozenlayer, xtremefile, gktorrent, redstartorrent, 32pages, underversel, prostylex, sukebei-pantsu, microbit, sktorrent, speedmasterhd, beyond-hd, amigosshare, dimeadozen, tlfbits, immortuos, romanianmetaltorrents, korsar, torrent-turk, hon3yhd, broadcity, torrentbd, hdstreet, ilcorsaroblu, cinemageddon, cpasbienclone, thepiratebay, hachede, springsunday, theplace, tapochek, metaltracker, asgaard, estone, leporno, hdtorrentsit, xiteme, ptfiles, extratorrent-cd, beitai, soundpark, yggcookie, karagarga, pterclub, desitorrents, pussytorrents, aftershock, mma-torrents, magnetdl, sexypics, linuxtracker, torrentquest, cartoonchaos, torrentz2k, hdturk, trezzor, extremlymtorrents, netlab, bitspyder, onlineselfeducation, fouducinema, pleasuredome, sukebeinyaasi, gay-torrentsorg, mactorrents, ilcorsaronero, hdreactor, torrentbomb, kickasstorrent, aniRena, RockBox, polishsource, torrentleech-pl, 0daykiev
10-23 21:26:33 Info Adding aggregate indexer
10-23 21:26:33 Info Jackett startup finished in 3.178 s
Hosting environment: Production
Content root path: /app/Jackett/Content
Now listening on: http://[::]:9117
Application started. Press Ctrl+C to shut down.
10-23 21:27:01 Info CardigannIndexer (beyond-hd): Relogin required
10-23 21:27:02 Error CardigannIndexer (beyond-hd): Found captcha during automatic login, aborting
10-23 21:27:02 Error Error on 20201023212702 for Beyond-HD.txtSystem.Exception: Relogin failed
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1369




<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url=https://beyond-hd.me/login" />

        <title>Redirecting to https://beyond-hd.me/login</title>
    </head>
    <body>
        Redirecting to <a href="https://beyond-hd.me/login">https://beyond-hd.me/login</a>.
    </body>
</html>
10-23 21:27:02 Error Jackett.Common.IndexerException: Exception (beyond-hd): Relogin failed
 ---> System.Exception: Parse error
 ---> System.Exception: Relogin failed
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1369
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 831
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1684
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 325
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 804
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 274
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26 Jackett.Common.IndexerException: Exception (beyond-hd): Relogin failed
 ---> System.Exception: Parse error
 ---> System.Exception: Relogin failed
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1369
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseWebIndexer.OnParseError(String results, Exception ex) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 831
   at Jackett.Common.Indexers.CardigannIndexer.PerformQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/CardigannIndexer.cs:line 1684
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 325
   --- End of inner exception stack trace ---
   at Jackett.Common.Indexers.BaseIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 345
   at Jackett.Common.Indexers.BaseWebIndexer.ResultsForQuery(TorznabQuery query) in /home/vsts/work/1/s/src/Jackett.Common/Indexers/BaseIndexer.cs:line 804
   at Jackett.Common.Services.IndexerManagerService.TestIndexer(String name) in /home/vsts/work/1/s/src/Jackett.Common/Services/IndexerManagerService.cs:line 274
   at Jackett.Server.Controllers.IndexerApiController.Test() in /home/vsts/work/1/s/src/Jackett.Server/Controllers/IndexerApiController.cs:line 130
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/vsts/work/1/s/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
10-23 21:27:15 Info Checking for updates... Jackett variant: CoreLinuxAmdx64
10-23 21:27:15 Info Updates are disabled via --NoUpdates.
```

**Comment by Roxedus** [comment]
Your image version is very outdated, please update your image
https://github.com/linuxserver/docker-jackett#via-docker-run

**Comment by aficiomaquinas** [comment]
I'm afraid there is something wrong that I'm doing, but it seems once I follow those steps I go back an old image version. What am I doing wrong. Sorry for the dumb question.
```
PS C:\Windows\system32> docker stop jackett
jackett
PS C:\Windows\system32> docker rm jackett
jackett
PS C:\Windows\system32> docker image prune
WARNING! This will remove all dangling images.
Are you sure you want to continue? [y/N] y
Total reclaimed space: 0B
PS C:\Windows\system32> docker pull linuxserver/jackett
Using default tag: latest
latest: Pulling from linuxserver/jackett
d2f5134e80cc: Pull complete
a453bd35b645: Pull complete
134faf5d1f70: Pull complete
8eed134df156: Pull complete
89aeb49a7056: Pull complete
28c641487f98: Pull complete
Digest: sha256:566b11c780e9f864004d782a0d3a2cd0b98cc7486d135cd67692fba86d64ce62
Status: Downloaded newer image for linuxserver/jackett:latest
docker.io/linuxserver/jackett:latest
PS C:\Windows\system32> docker create --name=jackett -e TZ=America/Mexico_City -e AUTO_UPDATE=true -p 9117:9117 -v W:/JackettConfig/config:/config -v C:/Users/Victor/Downloads:/downloads --restart unless-stopped linuxserver/jackett:development
7cf93b9f8d634f3c254f15895a13f41b28247c36beca04a0a3fc3cd0c1c07fe5
```

Logs:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
10-23 21:41:45 Info Starting Jackett v0.16.795.0
10-23 21:41:45 Info Environment version: 3.1.5 (/app/Jackett/)
10-23 21:41:46 Info OS version: Unix 4.19.76.0 (64bit OS) (64bit process)
10-23 21:41:46 Info Jackett variant: CoreLinuxAmdx64
10-23 21:41:46 Info File /etc/issue: Ubuntu 18.04.4 LTS \n \l
10-23 21:41:46 Info Running in Docker: Yes
10-23 21:41:46 Info ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
10-23 21:41:46 Info App config/log directory: /config/Jackett
10-23 21:41:46 Info Using Proxy: No
10-23 21:41:46 Error Your version of Jackett v0.16.795.0 is very old. Multiple indexers are likely to fail when using an old version. Update to the latest version of Jackett.
10-23 21:41:46 Info Using HTTP Client: HttpWebClient2NetCore
10-23 21:41:46 Info Loading Cardigann definitions from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
10-23 21:41:47 Info Cardigann definitions loaded: abnormal, alpharatio, anidex, anidub, animebytes, animetorrents, anthelion, avistaz, awesomehd, bakabt, bb, bitcityreloaded, bithdtv, bjshare, broadcasthenet, brokenstones, cgpeers, cinecalidad, cinemaz, corsarored, danishbits, digitalcore, digitalhive, divxtotal, elitetracker, epublibre, exoticaz, filelist, funfile, fuzer, gazellegames, gimmepeers, hdbitsapi, hdonly, hdspace, hdtorrents, hebits, horriblesubs, icetorrent, immortalseed, internetarchive, iptorrents, lostfilm, mejortorrent, milkie, morethantv, myamity, myanonamouse, ncore, nebulance, newpct, newrealworld, norbits, nordicbits, notwhatcd, orpheus, partis, passthepopcorn, pier720, piratethenet, pixelhd, polishtracker, pornolab, pretome, privatehd, psytorrents, rarbg, redacted, revolutiontt, rutracker, scenefz, scenehd, scenetime, secretcinema, shazbat, showrss, solidtorrents, speedcd, superbits, toloka, torrentbytes, torrentday, torrentech, torrentheaven, torrentleech, torrentnetwork, torrentscsv, torrentseeds, torrentsyndikat, tvstore, tvvault, xspeeds, xthor, xtremezone, yts, animetosho, yingk, focusx, peersfm, Das-Unerwartete, hddolby, mteamtp, btnext, uniongang, badasstorrents, omgwtftrackr, hddisk, torrentslocal, audiobooktorrents, acgsou, pirateiro, glodls, 3dtorrents, desireleasers, generationfree, eztv, twilightszoom, hdchina, empornium, idope, shareuniversity, torrenting, pornbits, torrent9clone, kinorun, xbytesv2, vizuk, firebit, turkseed, erzsebetpl, ehentai, gay-torrents, p2pelite, mononokebt, thevault, uhdbits, theaudioscene, wihd, hdcenter, nethd, wdt, pornolive, theshinning, insanetracker, yggtorrent, torrent4you, zamundanet, torrentkitty, bithumen, finvip, scenerush, pornbay, lechaudron, spiritofrevolution, cinematik, bithorlo, kaztorka, moecat, ourbits, pt99, hdc, twilight, academictorrents, libranet, limetorrents, zooqle, skytorrentsclone, zetorrents, onejav, asiancinema, bluebirdhd, hush, elitetorrent-biz, gfxpeers, lesaloon, bitturk, diablotorrent, mteamtp2fa, downloadville, thegeeks, noname-club, crazyspirits, magnet4you, itorrent, torrentseed, haidan, ydypt, totheglory, toros, thehorrorcharnel, rustorka, demonoid, shellife, torrentfunk, piratbit, movcr, empornium2fa, onlyscene, efectodoppler, topnow, ebooks-shares, takeabyte, 52pt, legacyhd, freetorrent, torrentland, torrentz2, sharewood, pwtorrents, legittorrents, thefallingangels, femdomcult, tvchaosuk, dragonworldreloaded, torrentdb, torlock, linkomanija, pornotor, torrentv, myspleen, 3evils, sdbits, demonsite, hdbitscom, ptmsg, btdb, galeriens, ethor, kapaki, greekteam, uniondht, crazyhd, hdcity, snowpt, dxp, casatorrent, darktracker, carpathians, eniahd, hd4fans, btgigs, bigfangroup, hdbits, newretro, Bittorrentfiles, ettv, audiobookbay, cztorrent, dmhy, kickasstorrent-kathow, theempire, fantasticheaven, booktracker, speedtorrentreloaded, marinetracker, moviesdvdr, rutracker-ru, cpasbien, tenyardtracker, mvgroupmain, xwtclassics, epizod, torrentproject2, bigtower, hqsource, torrent9, 4thd, soulvoice, magico, bteye, casstudiotv, alexfilm, newstudiol, torrentdownloads, zelkaorg, xfsub, film-paleis, underverse, oxtorrent, xxxtor, hdu, ebookparadijs, gamestorrents, yourbittorrent, extremebits, classix, anisource, brasiltracker, mvgroupforum, documentarytorrents, beyond-hd-oneurl, chilebt, tellytorrent, totallykids, u2, p2pbg, netcosmo, torrentccf, exttorrents, hdroute, torrentgalaxyorg, proaudiotorrents, 3changtrai, esharenet, datascene, torrent-pirat, concertos, scenepalace, gaytorrentru, r3vwtf, monova, hdsky, dxdhd, hamsterstudio, torrentparadise, crnaberza, baibako, learnflakes, bit-titan, hdhome, Channelx, bwtorrents, rptorrents, theoccult, tokyotosho, ttsweb, torrentlt, filebase, tasmanit, nyaa-pantsu, liaorencili, exkinoray, btetree, audionews, rus-media, keepfriends, hdtime, chdbits, tjupt, kinonavse100, 7torrents, nyaasi, siambit, nntt, purovicio, pthome, funkytorrents, acidlounge, racingforme, teamhd, bitru, blutopia, torrentview, muziekfabriek, teamos, ccfbits, rintor, iv-torrents, sportscult, ibit, rutor, parnuxi, nitro, theshow, ztracker, concen, newstudio, hdspain, divteam, aither, torrentfactory, sosulki, pornorip, torrentoyunindir, hdarea, 2fast4you, bigtorrent, world-of-tomorrow, gigatorrents, pctorrent, hdme, dark-shadow, torrentdownload, trancetraffic, hdolimpo, nbtorrents, puntorrent, majomparade, losslessclub, btsow, girotorrent, oshenpt, arabp2p, cinemamovies, seedfile, torrenthane, hdforever, btdigg, uniotaku, brobits, mypornclub, arenabg, u-torrents, 1337x, boxingtorrents, tekno3d, piratbitl, btschool, torrent-explosiv, horrorsite, pixelcove, turktorrent, shareisland, spacetorrent, jpopsuki, ast4u, torrenthr, backups, lastfiles, deildu, acgrip, kinozal, xwtorrents, sktorrent-org, pornleech, arabafenice, finelite, rapidzona, extremetorrents, racing4everyone, fullmixmusic, unlimitz, sporthd, erzsebet, xxxtorrents, hdzone, vhstapes, shokweb, bibliotik, tribalmixes, retroflix, filmsclub, pornforall, unionfansub, fanoin, inperil, riperam, leaguehd, torrentsectorcrew, ptsbao, isohunt2, frozenlayer, xtremefile, gktorrent, redstartorrent, 32pages, underversel, prostylex, sukebei-pantsu, microbit, sktorrent, speedmasterhd, beyond-hd, amigosshare, dimeadozen, tlfbits, immortuos, romanianmetaltorrents, korsar, torrent-turk, hon3yhd, broadcity, torrentbd, hdstreet, ilcorsaroblu, cinemageddon, cpasbienclone, thepiratebay, hachede, springsunday, theplace, tapochek, metaltracker, asgaard, estone, leporno, hdtorrentsit, xiteme, ptfiles, extratorrent-cd, beitai, soundpark, yggcookie, karagarga, pterclub, desitorrents, pussytorrents, aftershock, mma-torrents, magnetdl, sexypics, linuxtracker, torrentquest, cartoonchaos, torrentz2k, hdturk, trezzor, extremlymtorrents, netlab, bitspyder, onlineselfeducation, fouducinema, pleasuredome, sukebeinyaasi, gay-torrentsorg, mactorrents, ilcorsaronero, hdreactor, torrentbomb, kickasstorrent, aniRena, RockBox, polishsource, torrentleech-pl, 0daykiev
10-23 21:41:47 Info Adding aggregate indexer
10-23 21:41:47 Info Jackett startup finished in 3.164 s
Hosting environment: Production
Content root path: /app/Jackett/Content
Now listening on: http://[::]:9117
Application started. Press Ctrl+C to shut down.
```

**Comment by Roxedus** [comment]
pull the develop tag `docker pull linuxserver/jackett:development`

**Comment by aficiomaquinas** [comment]
Thanks a lot, sorry for my clumsiness.
