### ISSUE TITLE
[BUG] REDACTED.org no longer on list of indexers

### ISSUE THREAD

**Issue by godofjesters** [linuxserver/docker-jackett#154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

trying to add a second path in my indexers to REDACTED (currently i use REDACTED.cc) and want to add one to https://www. REDACTED.org/ since they are currently under a ddos and notice that torrentleech is no longer on the list. within the past couple days i've noticed that torrentleech doesn't even show up on my current list of indexers and have to restart the container to get it to show back up.

### Expected Behavior

REDACTED should appear on the list of indexers, including already set up indexers.

### Steps To Reproduce

1. install docker engine and run jackett using correctly configured run command
2. go to the webui for jackett
3. click on add indexer
4. search list for REDACTED. not REDACTED.pl

### Environment

```markdown
- OS: docker
- How docker service was installed: run command on debian 12
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run --restart always -d --name=jackett -v /opt/jackett:/config -v /mnt/path/to/my/sort/dir -e TZ=US/Pacific -e PUID=1000 -e PGID=100 -p 9117:9117 linuxserver/jackett
```

### Container logs

```bash
2024-10-07 11:58:06	Error	
FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.

[v0.22.722.0] FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass12_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 185
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 603
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin, String cookies) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 990
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.DoLogin(String cookies) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 607
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.ApplyConfiguration(JToken configJson) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 1066
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in ./Jackett.Server/Controllers/IndexerApiController.cs:line 97
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in ./Jackett.Server/Middleware/CustomExceptionHandler.cs:line 26
2024-10-07 11:54:49	Error	
Exception in GetConfigurationForSetup (torrentleech): FlareSolverrSharp.Exceptions.FlareSolverrException: FlareSolverr was unable to process the request, please check FlareSolverr logs. Message: Error: Error solving the challenge. Timeout after 55.0 seconds.
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass12_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at FlareSolverrSharp.Utilities.SemaphoreLocker.LockAsync[T](Func`1 worker)
   at FlareSolverrSharp.Solvers.FlareSolverr.SendFlareSolverrRequest(HttpContent flareSolverrRequest)
   at FlareSolverrSharp.Solvers.FlareSolverr.Solve(HttpRequestMessage request, String sessionId)
   at FlareSolverrSharp.ClearanceHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Jackett.Common.Utils.Clients.HttpWebClient2.Run(WebRequest webRequest) in ./Jackett.Common/Utils/Clients/HttpWebClient2.cs:line 180
   at Jackett.Common.Utils.Clients.WebClient.GetResultAsync(WebRequest request) in ./Jackett.Common/Utils/Clients/WebClient.cs:line 185
   at Jackett.Common.Indexers.BaseWebIndexer.RequestWithCookiesAsync(String url, String cookieOverride, RequestType method, String referer, IEnumerable`1 data, Dictionary`2 headers, String rawbody, Nullable`1 emulateBrowser) in ./Jackett.Common/Indexers/BaseIndexer.cs:line 603
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.GetConfigurationForSetup(Boolean automaticlogin, String cookies) in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 990
   at Jackett.Common.Indexers.Definitions.CardigannIndexer.GetConfigurationForSetup() in ./Jackett.Common/Indexers/Definitions/CardigannIndexer.cs:line 967
2024-10-07 11:46:27	Info	
Jackett startup finished in 5.816 s
2024-10-07 11:46:27	Info	
Adding filter indexer ('type:semi-public' indexer) ...
2024-10-07 11:46:27	Info	
Adding filter indexer ('type:private' indexer) ...
2024-10-07 11:46:27	Info	
Adding filter indexer ('type:public' indexer) ...
2024-10-07 11:46:27	Info	
Adding aggregate indexer ('all' indexer) ...
2024-10-07 11:46:27	Info	
Loaded 613 indexers in total
2024-10-07 11:46:27	Info	
Loaded 542 Cardigann indexers.
2024-10-07 11:46:23	Info	
Loading Cardigann indexers from: /config/cardigann/definitions/, /etc/xdg/cardigan/definitions/, /app/Jackett/Definitions
2024-10-07 11:46:23	Info	
Loaded 71 Native indexers.
2024-10-07 11:46:23	Info	
Loading Native indexers ...
2024-10-07 11:46:23	Info	
Using HTTP Client: HttpWebClient2
2024-10-07 11:46:23	Info	
Using FlareSolverr: http://192.168.150.3:8191
2024-10-07 11:46:23	Info	
Using proxy: Disabled
2024-10-07 11:46:23	Info	
App config/log directory: /config/Jackett
2024-10-07 11:46:23	Info	
ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2024-10-07 11:46:23	Info	
Running in Docker: Yes (image build: v0.22.722-ls552)
2024-10-07 11:46:23	Info	
File /etc/issue: Welcome to Alpine Linux 3.20
2024-10-07 11:46:23	Info	
Jackett variant: CoreLinuxMuslAmdx64
2024-10-07 11:46:23	Info	
OS version: Unix 6.1.0.26 (64bit OS) (64bit process)
2024-10-07 11:46:23	Info	
Environment version: 8.0.8 (/app/Jackett/)
2024-10-07 11:46:22	Info	
Starting Jackett v0.22.722
```

**Comment by Roxedus** [comment]
Report upstream, not a container issue.

**Comment by godofjesters** [comment]
thank you for your time
