### ISSUE TITLE
Error to fix on linuxserver

### ISSUE THREAD

**Issue by Anon0ne** [linuxserver/docker-jackett#97]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

https://github.com/Jackett/Jackett/pull/6779/commits/49404aafdde10ad76813db3202dec1ba6ae9a818
------------------------------

## Expected Behavior

Add the account...
## Steps to Reproduce

1. Try to add your DigitalCore account
2.
3.
4.

## Environment
**OS:**      LibreElec x64

## Docker logs

Jackett.Common.ExceptionWithConfigData: Invalid Captcha
   at Jackett.Common.Indexers.Digitalcore.<>c__DisplayClass8_0.<ApplyConfiguration>b__0() in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/digitalcore.cs:line 96
   at Jackett.Common.Indexers.BaseIndexer.ConfigureIfOK(String cookies, Boolean isLoggedin, Func`1 onError) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/BaseIndexer.cs:line 267
   at Jackett.Common.Indexers.Digitalcore.ApplyConfiguration(JToken configJson) in /home/appveyor/projects/jackett/src/Jackett.Common/Indexers/digitalcore.cs:line 98
   at Jackett.Server.Controllers.IndexerApiController.UpdateConfig(ConfigItem[] config) in /home/appveyor/projects/jackett/src/Jackett.Server/Controllers/IndexerApiController.cs:line 94
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jackett.Server.Middleware.CustomExceptionHandler.Invoke(HttpContext httpContext) in /home/appveyor/projects/jackett/src/Jackett.Server/Middleware/CustomExceptionHandler.cs:line 29

Here is the fix: https://github.com/Jackett/Jackett/pull/6779/commits/49404aafdde10ad76813db3202dec1ba6ae9a818

**Comment by aptalca** [comment]
So it's fixed upstream???

**Comment by aptalca** [comment]
Latest stable release was a day ago, so update your docker image and recreate your container

**Comment by Anon0ne** [comment]
I did update today, and it didn't help. Where are these cs files in your image? I will hunt it.

**Comment by aptalca** [comment]
They are part of the app, that we include in the docker image

**Comment by Anon0ne** [comment]
Okay. I was told via the Jackett github that the latest version is still not up to date for this fix. It's not resolved on this version.

**Comment by aptalca** [comment]
latest docker image has 0.12.1632
https://github.com/linuxserver/docker-jackett/releases/tag/v0.12.1632-ls51
